//! Log-mel spectrogram frontend for CLAP.
//!
//! This must byte-for-byte match HuggingFace `ClapFeatureExtractor` on the
//! non-fusion (`rand_trunc`) path, which is what the Xenova ONNX audio model
//! was traced with. Getting this wrong produces confidently-wrong embeddings
//! with no error, so every constant here is pinned to the reference and the
//! whole thing is golden-tested against Python fixtures in tests/clap_golden.rs.
//!
//! Reference: transformers.audio_utils.spectrogram + ClapFeatureExtractor with
//!   frame_length = 1024, hop = 480, power = 2.0, log_mel = "dB",
//!   center = True (reflect pad), periodic Hann window,
//!   slaney mel filterbank (norm="slaney", mel_scale="slaney"),
//!   fmin = 50, fmax = 14000, 64 mels, 48kHz.

use std::sync::Arc;

use rustfft::{num_complex::Complex64, Fft, FftPlanner};

pub const SAMPLE_RATE: u32 = 48_000;
pub const N_FFT: usize = 1024;
pub const HOP: usize = 480;
pub const N_MELS: usize = 64;
pub const N_FREQS: usize = N_FFT / 2 + 1; // 513
/// 10s at 48kHz — the fixed window length the audio tower expects.
pub const MAX_SAMPLES: usize = 480_000;
pub const N_FRAMES: usize = MAX_SAMPLES / HOP + 1; // 1001

const MEL_FLOOR: f32 = 1e-10;

/// Exact slaney filterbank from the reference, shape [N_FREQS x N_MELS] row-major.
/// Generated by tests/fixtures/clap/generate_fixtures.py's sibling step
/// (transformers.audio_utils.mel_filter_bank). Committed as a fixed asset so we
/// never re-derive the mel-scale math.
static MEL_FILTERS_BYTES: &[u8] = include_bytes!("mel_filters_slaney.bin");

/// Reusable mel frontend. Holds the FFT plan, window, and filterbank so a single
/// instance can be shared across worker threads (it is immutable after build).
pub struct MelFrontend {
    // FFT in f64 to match numpy (the reference promotes to float64 internally);
    // f32 diverges by ~0.02 dB after the log, which fails the parity gate.
    fft: Arc<dyn Fft<f64>>,
    window: Vec<f64>,
    /// [N_MELS][N_FREQS] — transposed filterbank for row-major mel accumulation.
    filters: Vec<[f64; N_FREQS]>,
}

impl MelFrontend {
    pub fn new() -> Self {
        assert_eq!(
            MEL_FILTERS_BYTES.len(),
            N_FREQS * N_MELS * 4,
            "mel filterbank asset has wrong size"
        );
        // Periodic Hann: np.hanning(N_FFT+1)[:-1] == 0.5 - 0.5*cos(2*pi*n/N_FFT).
        let window = (0..N_FFT)
            .map(|n| {
                0.5 - 0.5 * (2.0 * std::f64::consts::PI * n as f64 / N_FFT as f64).cos()
            })
            .collect();

        // File is [N_FREQS][N_MELS] row-major; transpose to [N_MELS][N_FREQS].
        let flat: Vec<f32> = MEL_FILTERS_BYTES
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect();
        let mut filters = vec![[0.0f64; N_FREQS]; N_MELS];
        for f in 0..N_FREQS {
            for m in 0..N_MELS {
                filters[m][f] = flat[f * N_MELS + m] as f64;
            }
        }

        let fft = FftPlanner::<f64>::new().plan_fft_forward(N_FFT);
        Self { fft, window, filters }
    }

    /// Compute the log-mel spectrogram for exactly `MAX_SAMPLES` samples.
    /// Returns a flat [N_FRAMES * N_MELS] row-major vector (frames-major),
    /// matching the reference `input_features` after its final transpose.
    pub fn log_mel(&self, samples: &[f32]) -> Vec<f32> {
        assert_eq!(samples.len(), MAX_SAMPLES, "log_mel expects a fixed window");

        // center = True: reflect-pad by N_FFT/2 on each side.
        let pad = N_FFT / 2;
        let padded = reflect_pad(samples, pad);

        let mut scratch = vec![Complex64::new(0.0, 0.0); N_FFT];
        let mut out = vec![0.0f32; N_FRAMES * N_MELS];

        for frame in 0..N_FRAMES {
            let start = frame * HOP;
            for i in 0..N_FFT {
                scratch[i] = Complex64::new(padded[start + i] as f64 * self.window[i], 0.0);
            }
            self.fft.process(&mut scratch);

            // Power spectrum over the one-sided bins, then mel + dB.
            let base = frame * N_MELS;
            for m in 0..N_MELS {
                let filt = &self.filters[m];
                let mut acc = 0.0f64;
                for f in 0..N_FREQS {
                    let c = scratch[f];
                    let power = c.re * c.re + c.im * c.im;
                    acc += filt[f] * power;
                }
                // mel_floor then power_to_db (reference=1.0): 10*log10(x).
                let v = acc.max(MEL_FLOOR as f64);
                out[base + m] = (10.0 * v.log10()) as f32;
            }
        }
        out
    }
}

impl Default for MelFrontend {
    fn default() -> Self {
        Self::new()
    }
}

/// Pad both ends by `pad` using numpy's default `reflect` mode (edge sample not
/// repeated): out = [x[pad], .., x[1], | x[0..n] | x[n-2], .., x[n-1-pad]].
fn reflect_pad(x: &[f32], pad: usize) -> Vec<f32> {
    let n = x.len();
    let mut out = Vec::with_capacity(n + 2 * pad);
    for i in 0..pad {
        out.push(x[pad - i]);
    }
    out.extend_from_slice(x);
    for i in 0..pad {
        out.push(x[n - 2 - i]);
    }
    out
}

/// Fit an arbitrary-length mono waveform to exactly `MAX_SAMPLES` for one embed
/// window. `> MAX_SAMPLES` callers should slice first; this handles the short
/// case with the reference `repeatpad` (tile then zero-pad).
pub fn fit_window(samples: &[f32]) -> Vec<f32> {
    if samples.len() == MAX_SAMPLES {
        return samples.to_vec();
    }
    if samples.len() > MAX_SAMPLES {
        return samples[..MAX_SAMPLES].to_vec();
    }
    if samples.is_empty() {
        return vec![0.0; MAX_SAMPLES];
    }
    // repeatpad: n_repeat = floor(max/len); tile n_repeat times, then zero-pad.
    let n_repeat = MAX_SAMPLES / samples.len();
    let mut out = Vec::with_capacity(MAX_SAMPLES);
    for _ in 0..n_repeat {
        out.extend_from_slice(samples);
    }
    out.resize(MAX_SAMPLES, 0.0);
    out
}
